### ISSUE TITLE
Decide on layout

### ISSUE THREAD

**Issue by rewardraj** [rewardraj/Bike-Rental-Service#1]

**Comment by Takuzwc** [comment]
so for renting a bike, we chose to have something like the cards highlighted in red, that will be able to scroll or have a button to move to the next cards. the card will have all information about the bike and the price to rent it. etc

we also chose the cards to look morden. lastly we want our nav bar to look like that in orange circle
![IMAGE 2022-10-30 20:51:38](https://user-images.githubusercontent.com/115803705/198898733-1850f000-5488-4519-bcfa-4904a305b9d2.jpg)
![IMAGE 2022-10-30 20:51:49](https://user-images.githubusercontent.com/115803705/198898741-6b9f5f93-75d3-487d-b3d2-51b09ac7fc71.jpg)

**Comment by Takuzwc** [comment]
The blue part will have images that change after a certain time
